In [1]:
#Alexandria Benedict, Assignment 5


from random import random
import nltk
import matplotlib.pyplot as plt
from nltk.probability import FreqDist
import pandas as pd
from math import log
from sklearn.model_selection import train_test_split
from collections import *
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
from sklearn import metrics

## Question 1

In [2]:

#Take in data
df1 = pd.read_csv('CONcreTEXT_trial_EN.tsv', sep='\t', header=None, engine= 'python')
df2 = pd.read_csv('CONcreTEXT_trial_IT.tsv', sep='\t', header=None, engine= 'python')


df1.at[0, 5] = "LANGUAGE"
df1[5][1:] = "English"
df2.at[0, 5] = "LANGUAGE"
df2[5][1:] = "Italian"
#df2.head()

df1.at[0, 6] = "CONCRETE"

row = 1
for i in df1[4][1:]:
    if float(df1[4][row]) <= 4:
        df1[6][row] = 'LOW'
    else:
        df1[6][row] = 'HIGH'
    #df1[6][row] = np.where(float(df1[4][row]) <= 4, 'LOW', 'HIGH')
    row += 1

df2.at[0, 6] = "CONCRETE"

row2 = 1
for i in df2[4][1:]:
    if float(df2[4][row2]) <= 4:
        df2[6][row2] = 'LOW'
    else:
        df2[6][row2] = 'HIGH'
    #df2[6][row2] = np.where(float(df2[4][row2]) <= 4, 'LOW', 'HIGH')
    row2 += 1



df = pd.concat([df1,df2])
df.at[0, 7] = "PREDICTIONS"
#print(df)
#print(len(df))
df.head()


0    1      2                                                  3  \
0       TARGET  POS  INDEX                                               TEXT   
1  achievement    N      3  Bring up academic achievements , awards , and ...   
2  achievement    N      9  Please list people you have helped , your pers...   
3     activate    V      1     Add activated carbon straight to your vodka .    
4     activate    V     15  Place sensors around your garden , and when a ...   

      4         5         6            7  
0  MEAN  LANGUAGE  CONCRETE  PREDICTIONS  
1  3.06   English       LOW          NaN  
2  3.03   English       LOW          NaN  
3  3.83   English       LOW          NaN  
4  5.51   English      HIGH          NaN

## Question 2

In [3]:
train, test = train_test_split(df, test_size=0.2, train_size = 0.8, random_state=42)


## Question 3

In [4]:
def majorityClass(train):
    row = 1
    high = 0
    low = 0
    for i in train[6][1:]:
        #print(i)
        if i == "HIGH":
            high += 1
        else:
            low += 1
        row += 1 
    #print("High: ", high)
    #print("Low: ", low)
    if high > low: 
        return "HIGH"
    else:
        return "LOW"
    

test[7][:] = majorityClass(train)

target_names = ["HIGH", "LOW"]
y_true = []
y_pred = []

for i in range(len(test)):
    y_pred.append(test[7].iloc[i])
    y_true.append(test[6].iloc[i])
#test.head()

print(metrics.classification_report(y_true, y_pred, target_names))

print(metrics.confusion_matrix(y_true, y_pred))

              precision    recall  f1-score   support

        HIGH       0.54      1.00      0.70        22
         LOW       0.00      0.00      0.00        19

    accuracy                           0.54        41
   macro avg       0.27      0.50      0.35        41
weighted avg       0.29      0.54      0.37        41

[[22  0]
 [19  0]]


C:\Users\meimei\anaconda3\lib\site-packages\pandas\core\series.py:1042: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_with(key, value)
C:\Users\meimei\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\meimei\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass labels=['HIGH', 'LOW'] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
C:\Users\meimei\anaconda

## Question 4

In [5]:
test.head()
row = 0
for i in test[0][1:]:
    #print(i)
    test[7].iloc[row] = np.where(len(test[0].iloc[row]) >= 5, 'HIGH', 'LOW')
    row += 1
test.head()


target_names = ["HIGH", "LOW"]
y_true = []
y_pred = []

for i in range(len(test)):
    y_pred.append(test[7].iloc[i])
    y_true.append(test[6].iloc[i])
#test.head()

print(metrics.classification_report(y_true, y_pred, target_names))

print(metrics.confusion_matrix(y_true, y_pred))

              precision    recall  f1-score   support

        HIGH       0.52      0.77      0.62        22
         LOW       0.38      0.16      0.22        19

    accuracy                           0.49        41
   macro avg       0.45      0.47      0.42        41
weighted avg       0.45      0.49      0.43        41

[[17  5]
 [16  3]]


<ipython-input-5-3dde5d2b8d0a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test[7].iloc[row] = np.where(len(test[0].iloc[row]) >= 5, 'HIGH', 'LOW')


## Question 5

In [6]:
#Text preprocessing
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df[3][:])
#X_train_counts.shape



tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

nb_train = []

for i in range(len(test)):
    #print(test[6].iloc[i])
    if test[6].iloc[i] == "HIGH":
        nb_train.append("HIGH")
    else:
        nb_train.append("LOW")
#print(nb_train)
#Train Naive Bayes Classifier
clf = MultinomialNB().fit(X_train_tfidf, df[6][:])

docs_new = []

for i in range(len(test)):
    docs_new.append(test[3].iloc[i])

#print(docs_new)


X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

predicted = clf.predict(X_new_tfidf)
y_pred = []
for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, category))
    y_pred.append(category)

    
    
print(metrics.classification_report(y_true, y_pred, target_names))

print(metrics.confusion_matrix(y_true, y_pred))

"If the roses are out of water even for a few minutes , they 'll suffer for it . " => HIGH
'Expenses include : rent , monthly loans , car insurance and car loans , health insurance and more . ' => HIGH
'Sleep is often disturbed by depression . ' => LOW
'Riduci i carboidrati raffinati e mangia più proteine magre e verdure . ' => HIGH
"Mentre alcuni avvocati rifiuteranno l' offerta , quelli con spirito imprenditoriale saranno deliziati dall' idea . " => LOW
'Osservare un campione al microscopio permette di focalizzarlo meglio e di analizzarlo in modo più particolareggiato . ' => HIGH
'Simply watching a movie or listening to music together are relaxing ways to enjoy each others company . ' => HIGH
'Non puoi fare due bracciate prendendo il respiro solo una volta , pena la squalifica . ' => LOW
'Organizza un programma per evitare di masturbarti in certi momenti della giornata . ' => HIGH
'There are some clocks that can safely have their minute hand turned counterclockwise . ' => HIGH
"You

C:\Users\meimei\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass labels=['HIGH', 'LOW'] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


## Question 6

In [7]:
test.head()
def thresholdClass(threshold):
    row = 0
    for i in test[0][1:]:
        #print(i)
        test[7].iloc[row] = np.where(len(test[0].iloc[row]) >= threshold, 'HIGH', 'LOW')
        row += 1
def getResults():
    y_true = []
    y_pred = []

    for i in range(len(test)):
        y_pred.append(test[7].iloc[i])
        y_true.append(test[6].iloc[i])

    print(metrics.classification_report(y_true, y_pred, target_names))
    print(metrics.confusion_matrix(y_true, y_pred))

    
thresholdClass(2)
getResults()

    
thresholdClass(5)
getResults()


thresholdClass(6)
getResults()

              precision    recall  f1-score   support

        HIGH       0.54      1.00      0.70        22
         LOW       0.00      0.00      0.00        19

    accuracy                           0.54        41
   macro avg       0.27      0.50      0.35        41
weighted avg       0.29      0.54      0.37        41

[[22  0]
 [19  0]]
              precision    recall  f1-score   support

        HIGH       0.52      0.77      0.62        22
         LOW       0.38      0.16      0.22        19

    accuracy                           0.49        41
   macro avg       0.45      0.47      0.42        41
weighted avg       0.45      0.49      0.43        41

[[17  5]
 [16  3]]
              precision    recall  f1-score   support

        HIGH       0.48      0.50      0.49        22
         LOW       0.39      0.37      0.38        19

    accuracy                           0.44        41
   macro avg       0.43      0.43      0.43        41
weighted avg       0.44      0.44   

<ipython-input-7-f474a9772aee>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test[7].iloc[row] = np.where(len(test[0].iloc[row]) >= threshold, 'HIGH', 'LOW')
C:\Users\meimei\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


I chose the thresholds above just to experiment values different from Question 4. Using a much smaller threshold such as 2 shows that there is very little to no classification to "LOW" as most words would be larger than 2 characters. As the threshold increases, you can see that there is more classifcation skewed to LOW rather than HIGH, as classifying words to the HIGH category would become more difficult with a higher threshold.